DEFAULT_ASCII_SET = "$@B%8&WM#*oahkbdpqwmZO0QLCJUYXzcvunxrjft/\\|()1{}[]?-_+~<>i!lI;:,\"^`'. "

CAMERA_WIDTH = 1280
CAMERA_HEIGHT = 720
TARGET_FPS = 30

TERMINAL_WIDTH_MARGIN = 1.0  
TERMINAL_HEIGHT_MARGIN = 1.0 
